# Generated by Django 2.1 on 2018-08-31 09:47

import ckeditor.fields
import datetime
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='news_photos')),
                ('content', ckeditor.fields.RichTextField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField(default=datetime.date.today)),
                ('viewcount', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
